kind: pipeline
name: default

steps:
- name: redis
  image: redis
  detach: true
  pull: if-not-exists

- name: test
  image: redis
  pull: if-not-exists
  commands:
  - sleep 5
  - redis-cli -h redis ping
  - redis-cli -h redis set FOO bar
  - redis-cli -h redis get FOO
