kind: pipeline
name: greeting

steps:
- name: en
  image: alpine:3.8
  commands:
  - echo hello
  - echo world
  - exit 1

---
kind: pipeline
name: saludo

steps:
- name: es
  image: alpine:3.8
  commands:
  - echo hola
  - echo mundo

---
kind: pipeline
name: salutation

steps:
- name: fr
  image: alpine:3.8
  commands:
  - echo bonjour
  - echo monde
  - echo $DRONE_BUILD_STATUS

trigger:
  status:
  - failure
  - success

depends_on:
- greeting
- saludo
