kind: pipeline
type: docker
name: foo

steps:
- name: foo
  image: alpine
  commands:
  - echo this should never run if branch is develop
  - echo the current branch is $DRONE_BRANCH

- name: bar
  image: alpine
  commands:
  - echo this should never run if branch is master
  - echo the current branch is $DRONE_BRANCH
  when:
    branch:
      exclude:
      - master
  

trigger:
  branch:
    exclude:
    - develop

---

kind: pipeline
type: docker
name: bar

steps:
- name: foo
  image: alpine
  commands:
  - echo this should never run if branch is master
  - echo the current branch is $DRONE_BRANCH

trigger:
  branch:
    exclude:
    - master
