kind: pipeline
type: docker
name: foo

steps:
- name: build
  image: alpine
  commands:
  - echo hello
  environment:
    AWS_ACCESS_KEY_ID: AKIAIOSFODNN7EXAMPLE

- name: test
  image: alpine
  commands:
  - echo world
  environment:
    AWS_ACCESS_KEY_ID: AKIAIOSFODNN7EXAMPLE

- name: scan
  image: plugins/gitleaks

