kind: pipeline
type: docker
name: default
steps:
- name: hello
  image: drone/this-image-does-not-exist # cause docker error
  commands:
  - echo hello
  
- name: world
  image: alpine
  commands:
  - echo world
