kind: pipeline
type: docker
name: default

steps:
  - name: hello
    image: alpine
    pull: if-not-exists
    commands:
    - echo hello
    - echo world

  - name: build
    image: plugins/docker
    settings:
      repo: foo/bar
      tags: latest
      dry_run: true
      debug: true
    volumes:
    - name: temp
      path: /tmp

  # - name: notify
  #   image: plugins/slack
  #   pull: if-not-exists
  #   settings:
  #     webhook:
  #       from_secret: slack_webhook
  #     channel: bradrydzewski
