kind: pipeline
name: default

steps:
- name: write
  image: alpine
  commands:
  - echo -n "this-is-a-test" > .tags

- name: build
  image: plugins/docker
  settings:
    dry_run: true
    repo: foo/bar
